Repository Agar-OSS/agartex-app, pull requests merged in 2023-06, with the labels that each got.

#54 Send client handshake message
  src/pages/main/Main.tsx
  src/pages/main/collaboration/collaboration.ts
  src/pages/main/collaboration/reducer/model.ts
  src/pages/main/collaboration/stream/stream.ts
Labels: enhancement

#62 Add userId to collaboration handshake
  src/pages/main/collaboration/reducer/model.ts
  src/pages/main/collaboration/stream/stream.ts
Labels: enhancement

#58 Resource-related UI
  src/components/editor/Editor.module.less
  src/components/editor/Editor.tsx
  src/components/editor/latex-textarea/LatexTextArea.tsx
  src/components/file-input/FileInput.module.less
  src/components/file-input/FileInput.tsx
  src/components/file-input/__test__/FileInput.test.tsx
  src/components/index.tsx
  src/model.ts
  src/pages/main/Main.module.less
  src/pages/main/Main.tsx
  src/pages/main/__test__/Main.test.tsx
  src/pages/main/toolbar/Toolbar.module.less
  src/pages/main/toolbar/Toolbar.tsx
  src/pages/main/toolbar/__test__/Toolbar.test.tsx
  src/pages/main/toolbar/resource-list/ResourceList.module.less
  src/pages/main/toolbar/resource-list/ResourceList.tsx
  src/pages/main/toolbar/resource-list/__test__/ResourceList.test.tsx
  src/pages/main/toolbar/resource-list/resource-tile/ResourceTile.module.less
  src/pages/main/toolbar/resource-list/resource-tile/ResourceTile.tsx
  src/pages/main/toolbar/resource-list/upload-resource-modal/UploadResourceModal.module.less
  src/pages/main/toolbar/resource-list/upload-resource-modal/UploadResourceModal.tsx
  src/pages/main/toolbar/resource-list/upload-resource-modal/__test__/UploadResourceModal.test.tsx
  src/pages/main/toolbar/service/resource-service.ts
  src/pages/projects/ProjectsPage.module.less
Labels: enhancement

#69 Design fixes
  src/components/editor/Editor.module.less
  src/components/editor/Editor.tsx
  src/components/editor/latex-textarea/LatexTextArea.tsx
  src/components/pdf-viewer/PdfViewer.module.less
  src/components/pdf-viewer/PdfViewer.tsx
  src/pages/main/Main.tsx
  src/pages/main/toolbar/Toolbar.tsx
  src/pages/main/toolbar/resource-list/ResourceList.module.less
  src/pages/main/toolbar/resource-list/ResourceList.tsx
  src/pages/main/toolbar/resource-list/__test__/ResourceList.test.tsx
  src/pages/projects/projects-list/ProjectsList.module.less
  src/pages/projects/projects-list/ProjectsList.tsx
  src/pages/projects/projects-list/__test__/ProjectsList.test.tsx
Labels: bug

#72 Integrate resource list with backend
  src/components/editor/Editor.tsx
  src/constants.ts
  src/pages/main/Main.tsx
  src/pages/main/service/compilation-service.ts
  src/pages/main/service/resource-service.ts
  src/pages/main/toolbar/Toolbar.tsx
Labels: enhancement

#57 Add basic hotkeys
  src/components/editor/latex-textarea/LatexTextArea.tsx
  src/components/editor/latex-textarea/MonacoContentManager.ts
  src/components/editor/latex-textarea/monaco-content-rules.ts
  src/pages/main/collaboration/collaboration.ts
  src/pages/main/collaboration/delta-queue/delta-queue.ts
  src/pages/main/collaboration/reducer/model.ts
  src/util/poly/poly.ts
Labels: enhancement

#73 Add lamport clocks
  src/components/editor/latex-textarea/MonacoContentManager.ts
  src/pages/main/collaboration/collaboration.ts
  src/pages/main/collaboration/delta-queue/delta-queue.ts
  src/pages/main/collaboration/reducer/actions.ts
  src/pages/main/collaboration/reducer/model.ts
Labels: bug, enhancement

#75 Adapt project list to new model
  src/components/editor/__test__/Editor.test.tsx
  src/model.ts
  src/pages/main/__test__/Main.test.tsx
  src/pages/main/toolbar/__test__/Toolbar.test.tsx
  src/pages/projects/projects-list/__test__/ProjectsList.test.tsx
  src/pages/projects/service/projects-service.ts
Labels: enhancement

#76 Pretty WebSocket status messages
  package-lock.json
  package.json
  src/components/alert/Alert.module.less
  src/components/alert/Alert.tsx
  src/components/alert/__test__/Alert.test.tsx
  src/components/editor/__test__/Editor.test.tsx
  src/components/editor/latex-textarea/LatexTextArea.module.less
  src/components/editor/latex-textarea/LatexTextArea.tsx
  src/components/editor/latex-textarea/cursors-decorations.ts
  src/components/index.tsx
  src/constants.ts
  src/global-styles.module.less
  src/pages/main/Main.module.less
  src/pages/main/Main.tsx
  src/pages/main/__test__/Main.test.tsx
  src/pages/main/collaboration/collaboration.ts
  src/pages/main/collaboration/reducer/actions.ts
  src/pages/main/collaboration/reducer/model.ts
Labels: enhancement

#78 Sort characters with same prevId and clock increasing by clientId
  src/components/editor/latex-textarea/MonacoContentManager.ts
Labels: bug

#81 Adjust protocol to fix concurrent inserts at the same position
  src/components/editor/latex-textarea/MonacoContentManager.ts
Labels: bug

#83 Fix errors on creating user
  src/components/text-input/TextInput.module.less
  src/pages/create-account/CreateAccountPage.module.less
Labels: bug
